# Generated by Django 4.2.7 on 2023-11-16 17:03

import course.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='no_of_module',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.upload_to),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=50)),
                ('quiz_deadline', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_quiz', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content', models.FileField(blank=True, null=True, upload_to='content/')),
                ('content_description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_content', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('explain_assignments', models.TextField()),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignment_files/')),
                ('due_date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('students', models.ManyToManyField(related_name='instructors_name', to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(related_name='course_assignment', to='course.assignment'),
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(related_name='course_content', to='course.content'),
        ),
        migrations.AddField(
            model_name='course',
            name='quizzes',
            field=models.ManyToManyField(related_name='course_quiz', to='course.quiz'),
        ),
    ]
