# Generated by Django 4.2.7 on 2023-11-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_no_of_module_alter_course_img_quiz_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
