# Generated by Django 4.2.7 on 2023-11-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_delete_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='img',
            new_name='course_image',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('business', 'Business'), ('it_and_software', 'IT and Software'), ('data_machine_learning', 'Data & Machine Learning'), ('design', 'Design'), ('marketing', 'Marketing'), ('cloud_devops', 'Cloud & DevOps'), ('cybersecurity', 'Cybersecurity'), ('life_skills', 'Life Skills')], default='development', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.CharField(blank=True, choices=[('completion', 'Upon Completion'), ('none', 'No Certificate')], default='none', max_length=50, null=True),
        ),
    ]
