# Generated by Django 4.2.7 on 2023-11-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_img_course_course_image_alter_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='no_of_module',
        ),
    ]
