# Generated by Django 4.2.7 on 2023-11-16 20:47

import course.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0006_remove_course_no_of_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to=course.models.upload_to),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(related_name='student_assignments', to='users.student'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
