# Generated by Django 4.2.7 on 2023-11-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_assignment_assignment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='quizzes',
        ),
    ]
