# Generated by Django 4.2.7 on 2023-11-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_course_assignments_remove_course_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
    ]
