# Generated by Django 4.2.7 on 2023-11-19 07:56

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz',
            field=models.FileField(blank=True, null=True, upload_to=course.models.upload_to),
        ),
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
