# Generated by Django 4.2.7 on 2023-11-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='enrolled_students',
            field=models.ManyToManyField(related_name='enrolled_students', to='users.student'),
        ),
    ]
