# Generated by Django 4.2.7 on 2023-11-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='course_id',
            new_name='course',
        ),
    ]
