# Generated by Django 4.2.7 on 2023-11-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('offer', '0004_rename_course_id_offer_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='waiting_list_status',
        ),
        migrations.AddField(
            model_name='offer',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, related_name='waiting_list_offers', to='users.student'),
        ),
    ]
