# Generated by Django 4.2.7 on 2023-11-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_remove_offer_waiting_list_status_offer_waiting_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='price',
            new_name='new_price',
        ),
    ]
